<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;
use App\Models\OrderItem;
use Carbon\Carbon;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        // Dữ liệu đơn hàng thực tế
        // user_id: 8-20 là customers
        // shop_id: 1-12 là active shops
        $orders = [
            [
                'order_code'       => 'FH-20240301-001',
                'user_id'          => 8,
                'shop_id'          => 1,
                'subtotal'         => 90000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 105000,
                'delivery_address' => '34 Lý Tự Trọng, Quận 1, TP.HCM',
                'customer_phone'   => '0911111111',
                'note'             => 'Ít đường, nhiều đá',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-03-01 08:15:00'),
                'delivered_at'     => Carbon::parse('2024-03-01 08:45:00'),
                'created_at'       => Carbon::parse('2024-03-01 08:00:00'),
                'items' => [
                    ['product_id'=>1,'product_name'=>'Trà sữa trân châu đường đen','product_price'=>45000,'quantity'=>2,'subtotal'=>90000],
                ],
            ],
            [
                'order_code'       => 'FH-20240302-002',
                'user_id'          => 9,
                'shop_id'          => 3,
                'subtotal'         => 120000,
                'shipping_fee'     => 15000,
                'discount'         => 15000,
                'total'            => 120000,
                'delivery_address' => '88 Nguyễn Đình Chiểu, Quận 3, TP.HCM',
                'customer_phone'   => '0912222222',
                'note'             => 'Thêm đồ chua',
                'voucher_code'     => 'SALE15K',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-03-02 11:20:00'),
                'delivered_at'     => Carbon::parse('2024-03-02 11:55:00'),
                'created_at'       => Carbon::parse('2024-03-02 11:00:00'),
                'items' => [
                    ['product_id'=>6,'product_name'=>'Cơm tấm sườn bì chả','product_price'=>55000,'quantity'=>1,'subtotal'=>55000],
                    ['product_id'=>9,'product_name'=>'Canh chua cá lóc','product_price'=>35000,'quantity'=>1,'subtotal'=>35000],
                    ['product_id'=>7,'product_name'=>'Cơm tấm sườn nướng đặc biệt','product_price'=>65000,'quantity'=>0,'subtotal'=>0],
                ],
            ],
            [
                'order_code'       => 'FH-20240303-003',
                'user_id'          => 10,
                'shop_id'          => 7,
                'subtotal'         => 67000,
                'shipping_fee'     => 10000,
                'discount'         => 0,
                'total'            => 77000,
                'delivery_address' => '15 Pasteur, Quận 1, TP.HCM',
                'customer_phone'   => '0913333333',
                'note'             => '',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-03-03 07:05:00'),
                'delivered_at'     => Carbon::parse('2024-03-03 07:25:00'),
                'created_at'       => Carbon::parse('2024-03-03 07:00:00'),
                'items' => [
                    ['product_id'=>15,'product_name'=>'Bánh mì thịt nguội đặc biệt','product_price'=>25000,'quantity'=>2,'subtotal'=>50000],
                    ['product_id'=>16,'product_name'=>'Bánh mì trứng ốp la','product_price'=>20000,'quantity'=>1,'subtotal'=>17000],
                ],
            ],
            [
                'order_code'       => 'FH-20240304-004',
                'user_id'          => 11,
                'shop_id'          => 5,
                'subtotal'         => 75000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 90000,
                'delivery_address' => '67 Lê Văn Sỹ, Quận Phú Nhuận, TP.HCM',
                'customer_phone'   => '0914444444',
                'note'             => 'Thêm tương ớt riêng',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-03-04 15:10:00'),
                'delivered_at'     => Carbon::parse('2024-03-04 15:40:00'),
                'created_at'       => Carbon::parse('2024-03-04 15:00:00'),
                'items' => [
                    ['product_id'=>10,'product_name'=>'Bánh tráng trộn đặc biệt','product_price'=>25000,'quantity'=>2,'subtotal'=>50000],
                    ['product_id'=>13,'product_name'=>'Khoai tây lắc phô mai','product_price'=>35000,'quantity'=>1,'subtotal'=>25000],
                ],
            ],
            [
                'order_code'       => 'FH-20240305-005',
                'user_id'          => 12,
                'shop_id'          => 11,
                'subtotal'         => 160000,
                'shipping_fee'     => 15000,
                'discount'         => 20000,
                'total'            => 155000,
                'delivery_address' => '200 Phan Văn Trị, Quận Bình Thạnh, TP.HCM',
                'customer_phone'   => '0915555555',
                'note'             => 'Để ở cổng giúp mình nhé',
                'voucher_code'     => 'LONGTEN20K',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-03-05 16:05:00'),
                'delivered_at'     => Carbon::parse('2024-03-05 16:40:00'),
                'created_at'       => Carbon::parse('2024-03-05 16:00:00'),
                'items' => [
                    ['product_id'=>18,'product_name'=>'Trà sữa oolong topping đặc biệt','product_price'=>55000,'quantity'=>2,'subtotal'=>110000],
                    ['product_id'=>20,'product_name'=>'Yakult dứa ổi','product_price'=>45000,'quantity'=>1,'subtotal'=>45000],
                    ['product_id'=>19,'product_name'=>'Brown sugar milk tea','product_price'=>50000,'quantity'=>0,'subtotal'=>0],
                ],
            ],
            [
                'order_code'       => 'FH-20240306-006',
                'user_id'          => 13,
                'shop_id'          => 3,
                'subtotal'         => 130000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 145000,
                'delivery_address' => '42 Trường Chinh, Quận Tân Bình, TP.HCM',
                'customer_phone'   => '0916666666',
                'note'             => '2 suất riêng, đóng hộp',
                'status'           => 'delivering',
                'confirmed_at'     => Carbon::parse('2024-03-06 12:10:00'),
                'created_at'       => Carbon::parse('2024-03-06 12:00:00'),
                'items' => [
                    ['product_id'=>6,'product_name'=>'Cơm tấm sườn bì chả','product_price'=>55000,'quantity'=>1,'subtotal'=>55000],
                    ['product_id'=>7,'product_name'=>'Cơm tấm sườn nướng đặc biệt','product_price'=>65000,'quantity'=>1,'subtotal'=>65000],
                    ['product_id'=>9,'product_name'=>'Canh chua cá lóc','product_price'=>35000,'quantity'=>0,'subtotal'=>0],
                ],
            ],
            [
                'order_code'       => 'FH-20240306-007',
                'user_id'          => 14,
                'shop_id'          => 1,
                'subtotal'         => 135000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 150000,
                'delivery_address' => '11 Nguyễn Thái Học, Quận 1, TP.HCM',
                'customer_phone'   => '0917777777',
                'note'             => '',
                'status'           => 'preparing',
                'confirmed_at'     => Carbon::parse('2024-03-06 14:32:00'),
                'created_at'       => Carbon::parse('2024-03-06 14:25:00'),
                'items' => [
                    ['product_id'=>1,'product_name'=>'Trà sữa trân châu đường đen','product_price'=>45000,'quantity'=>2,'subtotal'=>90000],
                    ['product_id'=>4,'product_name'=>'Trà đào cam sả','product_price'=>45000,'quantity'=>1,'subtotal'=>45000],
                ],
            ],
            [
                'order_code'       => 'FH-20240306-008',
                'user_id'          => 15,
                'shop_id'          => 7,
                'subtotal'         => 90000,
                'shipping_fee'     => 10000,
                'discount'         => 0,
                'total'            => 100000,
                'delivery_address' => '300 Lê Hồng Phong, Quận 10, TP.HCM',
                'customer_phone'   => '0918888888',
                'note'             => 'Giao trước 7h sáng',
                'status'           => 'confirmed',
                'confirmed_at'     => Carbon::parse('2024-03-06 06:35:00'),
                'created_at'       => Carbon::parse('2024-03-06 06:30:00'),
                'items' => [
                    ['product_id'=>15,'product_name'=>'Bánh mì thịt nguội đặc biệt','product_price'=>25000,'quantity'=>2,'subtotal'=>50000],
                    ['product_id'=>17,'product_name'=>'Bánh mì xíu mại','product_price'=>22000,'quantity'=>2,'subtotal'=>40000],
                ],
            ],
            [
                'order_code'       => 'FH-20240306-009',
                'user_id'          => 16,
                'shop_id'          => 5,
                'subtotal'         => 95000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 110000,
                'delivery_address' => '7 Nguyễn Cư Trinh, Quận 1, TP.HCM',
                'customer_phone'   => '0919999999',
                'note'             => 'Cay vừa thôi',
                'status'           => 'pending',
                'created_at'       => Carbon::parse('2024-03-06 16:50:00'),
                'items' => [
                    ['product_id'=>11,'product_name'=>'Xúc xích nướng 5 cái','product_price'=>30000,'quantity'=>2,'subtotal'=>60000],
                    ['product_id'=>12,'product_name'=>'Trứng cút lắc muối tắc','product_price'=>20000,'quantity'=>1,'subtotal'=>20000],
                    ['product_id'=>14,'product_name'=>'Bắp xào bơ đặc biệt','product_price'=>25000,'quantity'=>1,'subtotal'=>15000],
                ],
            ],
            [
                'order_code'       => 'FH-20240306-010',
                'user_id'          => 17,
                'shop_id'          => 11,
                'subtotal'         => 100000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 115000,
                'delivery_address' => '55 Bà Huyện Thanh Quan, Quận 3, TP.HCM',
                'customer_phone'   => '0920000000',
                'note'             => '',
                'status'           => 'pending',
                'created_at'       => Carbon::parse('2024-03-06 17:10:00'),
                'items' => [
                    ['product_id'=>19,'product_name'=>'Brown sugar milk tea','product_price'=>50000,'quantity'=>2,'subtotal'=>100000],
                ],
            ],
            // đơn đã huỷ
            [
                'order_code'       => 'FH-20240228-011',
                'user_id'          => 18,
                'shop_id'          => 1,
                'subtotal'         => 85000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 100000,
                'delivery_address' => '120 Nguyễn Thị Minh Khai, Quận 3, TP.HCM',
                'customer_phone'   => '0921111111',
                'note'             => '',
                'status'           => 'cancelled',
                'cancel_reason'    => 'Khách huỷ do bận việc đột xuất',
                'created_at'       => Carbon::parse('2024-02-28 10:00:00'),
                'items' => [
                    ['product_id'=>2,'product_name'=>'Matcha latte trân châu','product_price'=>50000,'quantity'=>1,'subtotal'=>50000],
                    ['product_id'=>3,'product_name'=>'Hồng trà sữa','product_price'=>40000,'quantity'=>1,'subtotal'=>35000],
                ],
            ],
            [
                'order_code'       => 'FH-20240227-012',
                'user_id'          => 19,
                'shop_id'          => 3,
                'subtotal'         => 55000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 70000,
                'delivery_address' => '88 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM',
                'customer_phone'   => '0922222222',
                'note'             => '',
                'status'           => 'cancelled',
                'cancel_reason'    => 'Shop hết nguyên liệu sườn bì chả',
                'created_at'       => Carbon::parse('2024-02-27 11:30:00'),
                'items' => [
                    ['product_id'=>6,'product_name'=>'Cơm tấm sườn bì chả','product_price'=>55000,'quantity'=>1,'subtotal'=>55000],
                ],
            ],
            [
                'order_code'       => 'FH-20240225-013',
                'user_id'          => 20,
                'shop_id'          => 5,
                'subtotal'         => 50000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 65000,
                'delivery_address' => '55 Bà Huyện Thanh Quan, Quận 3, TP.HCM',
                'customer_phone'   => '0922222222',
                'note'             => '',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-25 15:05:00'),
                'delivered_at'     => Carbon::parse('2024-02-25 15:35:00'),
                'created_at'       => Carbon::parse('2024-02-25 15:00:00'),
                'items' => [
                    ['product_id'=>10,'product_name'=>'Bánh tráng trộn đặc biệt','product_price'=>25000,'quantity'=>2,'subtotal'=>50000],
                ],
            ],
            [
                'order_code'       => 'FH-20240224-014',
                'user_id'          => 8,
                'shop_id'          => 11,
                'subtotal'         => 110000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 125000,
                'delivery_address' => '34 Lý Tự Trọng, Quận 1, TP.HCM',
                'customer_phone'   => '0911111111',
                'note'             => 'Trân châu nhiều nhé',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-24 09:10:00'),
                'delivered_at'     => Carbon::parse('2024-02-24 09:45:00'),
                'created_at'       => Carbon::parse('2024-02-24 09:00:00'),
                'items' => [
                    ['product_id'=>18,'product_name'=>'Trà sữa oolong topping đặc biệt','product_price'=>55000,'quantity'=>1,'subtotal'=>55000],
                    ['product_id'=>20,'product_name'=>'Yakult dứa ổi','product_price'=>45000,'quantity'=>1,'subtotal'=>45000],
                ],
            ],
            [
                'order_code'       => 'FH-20240223-015',
                'user_id'          => 9,
                'shop_id'          => 7,
                'subtotal'         => 47000,
                'shipping_fee'     => 10000,
                'discount'         => 0,
                'total'            => 57000,
                'delivery_address' => '88 Nguyễn Đình Chiểu, Quận 3, TP.HCM',
                'customer_phone'   => '0912222222',
                'note'             => '',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-23 06:35:00'),
                'delivered_at'     => Carbon::parse('2024-02-23 06:55:00'),
                'created_at'       => Carbon::parse('2024-02-23 06:30:00'),
                'items' => [
                    ['product_id'=>16,'product_name'=>'Bánh mì trứng ốp la','product_price'=>20000,'quantity'=>1,'subtotal'=>20000],
                    ['product_id'=>17,'product_name'=>'Bánh mì xíu mại','product_price'=>22000,'quantity'=>1,'subtotal'=>22000],
                    ['product_id'=>15,'product_name'=>'Bánh mì thịt nguội đặc biệt','product_price'=>25000,'quantity'=>0,'subtotal'=>5000],
                ],
            ],
            [
                'order_code'       => 'FH-20240222-016',
                'user_id'          => 10,
                'shop_id'          => 1,
                'subtotal'         => 95000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 110000,
                'delivery_address' => '15 Pasteur, Quận 1, TP.HCM',
                'customer_phone'   => '0913333333',
                'note'             => 'Không đường',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-22 14:15:00'),
                'delivered_at'     => Carbon::parse('2024-02-22 14:50:00'),
                'created_at'       => Carbon::parse('2024-02-22 14:00:00'),
                'items' => [
                    ['product_id'=>3,'product_name'=>'Hồng trà sữa','product_price'=>40000,'quantity'=>2,'subtotal'=>80000],
                    ['product_id'=>5,'product_name'=>'Cà phê sữa đá cuộn','product_price'=>35000,'quantity'=>0,'subtotal'=>15000],
                ],
            ],
            [
                'order_code'       => 'FH-20240221-017',
                'user_id'          => 11,
                'shop_id'          => 3,
                'subtotal'         => 165000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 180000,
                'delivery_address' => '67 Lê Văn Sỹ, Quận Phú Nhuận, TP.HCM',
                'customer_phone'   => '0914444444',
                'note'             => '3 suất cho cả nhóm',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-21 11:05:00'),
                'delivered_at'     => Carbon::parse('2024-02-21 11:40:00'),
                'created_at'       => Carbon::parse('2024-02-21 11:00:00'),
                'items' => [
                    ['product_id'=>6,'product_name'=>'Cơm tấm sườn bì chả','product_price'=>55000,'quantity'=>2,'subtotal'=>110000],
                    ['product_id'=>8,'product_name'=>'Cơm gà rau sống','product_price'=>50000,'quantity'=>1,'subtotal'=>50000],
                    ['product_id'=>9,'product_name'=>'Canh chua cá lóc','product_price'=>35000,'quantity'=>0,'subtotal'=>5000],
                ],
            ],
            [
                'order_code'       => 'FH-20240220-018',
                'user_id'          => 12,
                'shop_id'          => 5,
                'subtotal'         => 70000,
                'shipping_fee'     => 15000,
                'discount'         => 0,
                'total'            => 85000,
                'delivery_address' => '200 Phan Văn Trị, Quận Bình Thạnh, TP.HCM',
                'customer_phone'   => '0915555555',
                'note'             => '',
                'status'           => 'delivered',
                'confirmed_at'     => Carbon::parse('2024-02-20 16:05:00'),
                'delivered_at'     => Carbon::parse('2024-02-20 16:35:00'),
                'created_at'       => Carbon::parse('2024-02-20 16:00:00'),
                'items' => [
                    ['product_id'=>11,'product_name'=>'Xúc xích nướng 5 cái','product_price'=>30000,'quantity'=>2,'subtotal'=>60000],
                    ['product_id'=>14,'product_name'=>'Bắp xào bơ đặc biệt','product_price'=>25000,'quantity'=>0,'subtotal'=>10000],
                ],
            ],
        ];

        foreach ($orders as $orderData) {
            $items = $orderData['items'];
            unset($orderData['items']);

            $order = Order::create($orderData);

            foreach ($items as $item) {
                if ($item['quantity'] > 0) {
                    OrderItem::create(array_merge($item, ['order_id' => $order->id]));
                }
            }
        }

        $this->command->info('✅ OrderSeeder: Đã tạo ' . count($orders) . ' orders với các order items');
    }
}
